version: '3.8'

services:
  database:
    build: .
    restart: on-failure
    shm_size: 16g
    mem_limit: 16g
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demo
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
