version: '3.8'

services:
  database:
    image: postgres:15.3-bullseye
    restart: on-failure
    shm_size: 16g
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demo
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]

